import type { Locale } from "@/lib/i18n";
import Link from "next/link";
import { getCopy } from "@/lib/i18n";
import { AppHeader } from "@/components/layout/AppHeader";
import { PageTopbar } from "@/components/layout/PageTopbar";
import { PublicFooter } from "@/components/layout/PublicFooter";
import { CookiePreferences } from "@/components/content/CookiePreferences";

type PolicyKind = "privacy" | "terms" | "cookies" | "help";

const content = {
  privacy: {
    th: { title: "ศูนย์ความเป็นส่วนตัว", intro: "คำอธิบายนี้ตรงกับข้อมูลและการทำงานของ ParkSpace MSU ในระบบปัจจุบัน ส่วนประกาศคุ้มครองข้อมูลส่วนบุคคลของมหาวิทยาลัยให้ยึดเอกสารทางการของ มมส.", sections: [["ข้อมูลที่ระบบเก็บ", "บัญชีผู้ใช้ เช่น อีเมล ชื่อ รหัสนิสิต/บุคลากร คณะ สาขา และเบอร์โทรศัพท์; ข้อมูลรถ เช่น ทะเบียน จังหวัด ประเภทรถ ยี่ห้อ รุ่น และสี; รวมถึงวันเวลา พื้นที่ ช่องจอด รายการรถที่ใช้ Booking Reference สถานะ QR การสแกน Check-in/Check-out ความคิดเห็น และตัวเลือกคุกกี้ที่จำเป็นต่อบริการ"], ["วัตถุประสงค์และการเข้าถึง", "ใช้เพื่อค้นหาและจองพื้นที่ จัดการช่องจอด ตรวจสอบรถและ QR ดูแลความปลอดภัย แก้ปัญหา และทำ audit เฉพาะผู้มีสิทธิ์ ข้อมูลรถและการจองไม่แสดงต่อสาธารณะ; เจ้าของบัญชีเห็นข้อมูลของตน ส่วน Admin/เจ้าหน้าที่/Developer เห็นได้ตามสิทธิ์ที่กำหนด"], ["การควบคุมข้อมูล", "ผู้ใช้แก้ไขข้อมูลโปรไฟล์และรถของตนได้ ปรับตัวเลือกคุกกี้ได้จากหน้านี้ และแจ้งปัญหาหรือขอให้ตรวจสอบข้อมูลได้ผ่าน Help/แจ้งบัก ระบบจะบันทึกประวัติความยินยอมและ audit สำหรับการดำเนินการสำคัญ"]] },
    en: { title: "Privacy Center", intro: "This description matches the data and behavior currently implemented in ParkSpace MSU. For Mahasarakham University’s official privacy notice, use the university’s official PDPA documents.", sections: [["Data collected", "Account data such as email, name, university ID, faculty, major, and phone; vehicle data such as plate, province, type, brand, model, and color; plus booking date/time, area, slot, vehicle snapshot, Booking Reference, QR status, scans, check-in/out, feedback, and service cookie choices."], ["Purpose and access", "Used to search and reserve parking, manage slots, verify vehicles and QR passes, operate securely, resolve issues, and maintain audit records. Vehicle and booking data is not public; account owners see their own data, while Admin, staff, and Developer access is limited by role."], ["Your controls", "Users can update their own profile and vehicles, change cookie choices on this page, report issues, and request a data review through Help. Consent and important operational changes are recorded for accountability."]] },
  },
  terms: {
    th: { title: "ข้อกำหนดการใช้งาน", intro: "ข้อกำหนดนี้อธิบายการใช้งาน ParkSpace MSU ที่เปิดไว้ในระบบ ผู้ใช้ต้องปฏิบัติตามประกาศและคำแนะนำของกองอาคารสถานที่ มมส. ณ พื้นที่จริงด้วย", sections: [["การจองและช่องจอด", "ตรวจสอบวันที่ เวลา พื้นที่ ช่องจอด และรถก่อนยืนยัน การจองที่สำเร็จเป็นรายการจริงในระบบและช่องเดียวกันจะถูกกันซ้ำตามช่วงเวลา หากยกเลิกหรือหมดอายุ สถานะจะเปลี่ยนตามกติกาของระบบ"], ["QR Pass และการเข้าพื้นที่", "QR ใช้ยืนยัน Booking กับเจ้าหน้าที่ ห้ามส่งต่อหรือเผยแพร่ เจ้าหน้าที่สามารถตรวจสอบพื้นที่ รถ และช่วงเวลาได้ ระบบบันทึกการสแกน Check-in/Check-out และเหตุการณ์ที่เกี่ยวข้อง"], ["ข้อมูล Mockup", "เฉพาะผัง A–G และจำนวน 100 ช่องต่อพื้นที่ที่มีป้าย Mockup เป็นข้อมูลตัวอย่างเพื่อทดสอบหน้าจอ ส่วนการจอง สถานะตามช่วงเวลา QR และประวัติการใช้งานเป็นข้อมูลระบบจริงเมื่อเชื่อมฐานข้อมูล"]] },
    en: { title: "Terms of service", intro: "These terms describe the ParkSpace MSU features currently exposed. Users must also follow MSU Building and Grounds instructions at the physical parking area.", sections: [["Bookings and slots", "Check the date, time, area, slot, and vehicle before confirming. A successful booking is a real system record and the same slot is protected against overlapping active bookings. Cancellation and expiry follow the system rules."], ["QR Pass and gate access", "A QR pass verifies a booking with staff. Do not share or publish it. Staff may verify the area, vehicle, and time window; scans, check-in/out, and related events are recorded."], ["Mockup data", "Only the A–G layout and 100-space capacity per area labelled Mockup are sample data for the interface. Bookings, time-based status, QR, and usage history are real system records once the database is connected."]] },
  },
  cookies: {
    th: { title: "นโยบายคุกกี้", intro: "ระบบจะแยกคุกกี้ที่จำเป็นออกจากคุกกี้วิเคราะห์และการตั้งค่า ผู้ใช้เปลี่ยนแปลงได้จาก Cookie Settings", sections: [["Necessary", "จำเป็นต่อการเข้าสู่ระบบ ความปลอดภัย และการทำงานหลัก ปิดไม่ได้"], ["Analytics", "เปิดหรือปิดได้ และต้องบันทึกความยินยอม"], ["Preferences / Performance", "ใช้จำภาษาและปรับปรุงประสบการณ์ตามการตั้งค่าของผู้ใช้"]] },
    en: { title: "Cookie policy", intro: "The system separates necessary, analytics, preference, and performance cookies. Users can change settings in Cookie Settings.", sections: [["Necessary", "Required for sign-in, security, and core functions; always on."], ["Analytics", "Optional and controlled by consent."], ["Preferences / Performance", "Used for language preferences and service improvement according to user settings."]] },
  },
  help: {
    th: { title: "ช่วยเหลือและติดต่อ", intro: "ช่องทางช่วยเหลือสำหรับปัญหาการจอง การสแกน QR ความปลอดภัย และข้อมูลส่วนตัว", sections: [["ปัญหาการจอง", "ตรวจสอบหน้า การจองของฉัน และหมายเลข Booking ก่อนติดต่อเจ้าหน้าที่ หรือใช้หน้าแจ้งบักเพื่อบันทึกปัญหาเข้าระบบ"], ["ปัญหา QR", "แจ้ง Booking Reference หรือ QR Reference แทนการส่งข้อมูลส่วนตัวทั้งหมด และแสดง QR ให้เจ้าหน้าที่ตรวจสอบที่จุดเข้าใช้"], ["ติดต่อกองอาคารสถานที่ มมส.", "สำนักงานกองอาคารสถานที่ โทร. 043 719 800 ต่อ 1271, 1272 · ศูนย์บริการ โทร. 043 719 800 ต่อ 1352 · เว็บไซต์ building.msu.ac.th"]] },
    en: { title: "Help & contact", intro: "Support for booking, QR scanning, safety, and privacy issues.", sections: [["Booking issue", "Check My Bookings and your Booking Reference, or submit a bug report so the issue is recorded in the system."], ["QR issue", "Share a Booking Reference or QR Reference instead of sending personal data, and show the QR to staff at the gate."], ["MSU Building and Grounds contact", "Building and Grounds Office: 043 719 800 ext. 1271, 1272 · Service Center: 043 719 800 ext. 1352 · building.msu.ac.th"]] },
  },
} as const;

export function PolicyPage({ locale, kind }: { locale: Locale; kind: PolicyKind }) {
  const t = getCopy(locale);
  const selected = content[kind][locale];
  return <div className="app-frame"><div className="page-wrap"><AppHeader locale={locale} /><PageTopbar locale={locale} title={selected.title} subtitle={kind === "privacy" ? "Version-managed · Admin managed" : t.realDataNote} /><div className="legal-card"><div className="mockup-note">{selected.intro}</div>{selected.sections.map(([heading, body]) => <section key={heading}><h2>{heading}</h2><p>{body}</p></section>)}{kind === "privacy" ? <p className="policy-source">{locale === "th" ? "เอกสาร PDPA ทางการของมหาวิทยาลัยมหาสารคาม: " : "Official Mahasarakham University PDPA resources: "}<a href="https://pdpa.msu.ac.th/" target="_blank" rel="noreferrer">pdpa.msu.ac.th</a></p> : null}{kind === "help" ? <div className="support-actions"><Link className="primary-button" href={`/${locale}/report-bug`}>{t.reportBug}</Link><Link className="secondary-button" href={`/${locale}/feedback`}>{t.rateExperience}</Link></div> : null}</div>{kind === "cookies" ? <CookiePreferences locale={locale} /> : null}<PublicFooter locale={locale} /></div></div>;
}
